export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const VERIFY_PROFILE = 'VERIFY_PROFILE';
export const VERIFY_PROFILE_SUCCESS = 'VERIFY_PROFILE_SUCCESS';
export const VERIFY_PROFILE_FAIL = 'VERIFY_PROFILE_FAIL';